### ISSUE TITLE
Whitelabelling - Ability to change colours and logos in Coral interface app

### ISSUE THREAD

**Issue by elaineg** [cohere-ai/cohere-toolkit#12]
### What feature(s) would you like to see?

Current behaviour: Users cannot change the colours and logos used within in the Coral application to make the interface fit their brand better.

### Additional information

Expected behaviour: Users should have the option to change the following: 
    1. Define primary and secondary colour groups
    2. Add a different logo in the top lefthand corner

**Comment by lakshyaag** [comment]
When and how do we expect the user to change the theme and logo, i.e., before running `docker compose` to view the application, or once the application is running? 

For the logo in the top lefthand corner, we could add another flag to `Logo.tsx` in `src/components/Shared` to check if the user has passed a custom logo directory to read from that, otherwise display the default SVGs. This would require updating the environment variables to accept another feature flag. Happy to work on this with more clarity!

For themes, users can change the `cohereTheme.js` or add a new file and accordingly update the `tailwind.config.js` file.

**Comment by elaineg** [comment]
Hi! I'd like this to be configurable after the application is running, it should not need to be configured during/prior to make first-run. 

> For the logo in the top lefthand corner, we could add another flag to Logo.tsx in src/components/Shared to check if the user has passed a custom logo directory to read from that, otherwise display the default SVGs. This would require updating the environment variables to accept another feature flag. Happy to work on this with more clarity!
This looks like reasonable scope! 

@wujessica  Any thoughts on the implementation here? 

And good call on the theme changing, I think we can just add documentation

**Comment by lakshyaag** [comment]
Awesome, I'll push a change for the theme documentation soon and wait for comments on the logo implementation!

**Comment by lakshyaag** [comment]
@wujessica: opened up #113 with the logo edits - we could merge #87 first, then #113 if all looks good!

**Comment by lakshyaag** [comment]
Apologies for the back-and-forth with the commits @wujessica - I've closed the previous 2 PRs and opened a single one #123 with the same edits. Commits should be signed now.

**Comment by lakshyaag** [comment]
This is merged - let me know if there's anything else on this or if we're closing this issue!

**Comment by tianjing-li** [comment]
@lakshyaag This is now merged, thank you for your contributions Lakshya they are very appreciated! Closing this.
