### ISSUE TITLE
Update ui to the latest from corel.com

### ISSUE THREAD

**Issue by EeroEternal** [cohere-ai/cohere-toolkit#74]
### What feature(s) would you like to see?

The web ui is not the latest one at https://coral.cohere.com/. Can it be updated?

**Comment by BeatrixCohere** [comment]
Hi, thanks for trying out the toolkit. We are working on parity; which features would you like to see in particular?

**Comment by EeroEternal** [comment]
I prefer file upload in the right sidebar

**Comment by elaineg** [comment]
@EeroEternal LOL that is one of the only new features we added to Cohere Toolkit 😭 Thanks for the feedback though. I thought it would be better next to the composer because it's similar to slack/messaging apps, and you can see where in the chat it was added. Do you mind sharing why you prefer upload in the sidebar? (You will still see the files in the chat in the sidebar).

**Comment by EeroEternal** [comment]
Placing it in the sidebar can display the file more clearly. Put it in the chat box. If there are a lot of words, it will be messy now.

**Comment by elaineg** [comment]
The files are still in the sidebar! And I would agree to any change to label the file attachment icon so that is more clear.
