### ISSUE TITLE
Unable to copy text from user/model in conversations

### ISSUE THREAD

**Issue by tylerjthomas9** [cohere-ai/cohere-toolkit#797]
### What is the issue?

I have a local deployment of the cohere toolkit, and I am unable to copy text that I have previously sent in the chat, or text that the model has outputted. I do not get the text in my clipboard when I highlight it and copy it with control+c / right click + copy.  The same applies for the copy button next to the text, nothing happens.

### Additional information

Here is an image of the UI with the copy button I am referring to

![image](https://github.com/user-attachments/assets/fd51da42-1dfa-435e-9f56-ab4b25289661)

**Comment by malexw** [comment]
This seems to be working for me on the latest version of Toolkit. What browser and OS are you using?

Toolkit doesn't do anything to interfere with the browser or OS copy / paste functionality so I'm suspicious that this is something specific to your machine.

**Comment by tylerjthomas9** [comment]
The toolkit is running on a Ubuntu server, and I am trying it with Firefox/Chrome/Edge on Windows 11. I will try different setups and get back to you.

**Comment by malexw** [comment]
That log is helpful, thanks! It turns out I misspoke; we do intercept cut/copy, so this is a real bug. The underlying issue likely is that JS isn't allowed to access the clipboard on pages loaded over HTTP, so you'll need to upgrade to HTTPS in the end to make it work. However, on Toolkit's side, we can make this failure more obvious.
